print("Hey there!")
import time
time.sleep(1)
print("This is your money managing bot.")
time.sleep(1)
name = input("What's your name?: ")
print("Nice to meet you", name)
time.sleep(1)
print("$Manager: Let's get started,")
curr = input("Your Currency eg:USD-GBP-EUR: ")
balance = input("Ammount of money you have: ")
wantmoney = input("Insert ammount of money you want to save up for: ")
if balance > wantmoney:
    print("Error! You can't do that")
    time.sleep(3)
    exit()
canwait = input("Number of days you can wait for: ")
print("$Manager: So you have", balance, curr,"want",wantmoney, curr,)
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("$Manager: Let's calculate!")
time.sleep(2)
D = 'D'
M = 'M'
Y = 'Y'
method = input("Method of time you want to use ex:(D-M-Y): ")
if method == D:
    final1 = int(wantmoney) - int(balance)
    print("$Manager: You need",final1,curr," in",canwait,"days")
    dconvert = input("Number of days you can wait: ")
    print("$Manager: You need to save up", final1, curr," in", dconvert, "days!")
    print("$Manager: Which means,")
    time.sleep(1)
    final11 = float(final1) / float(dconvert)
    print("You need to save:",final11,curr,"in a day, for", dconvert," days")
    time.sleep(2)
    print("Please copy the information down.")
    time.sleep(10)
    print("Thank you for using $Manager!")
if method == M:
    final2 = float(wantmoney) - float(balance)
    print("$Manager: You need", final2, curr," in", canwait, "days")
    monthwait = input("Number of months you can wait: ")
    mconvert1 = int(monthwait) * int(1)
    mconvert2 = int(mconvert1) / int(final2)
    print("$Manager: You need to save up",final2,curr," in",mconvert1,"months!")
    time.sleep(1)
    print("Which means,")
    time.sleep(1)
    final22 = float(final2) / float(monthwait)
    print("You need to save:",final22, curr,"a month, for",monthwait,"months!")
    time.sleep(2)
    print("Please copy the information down.")
    time.sleep(10)
    print("Thank you for using $Manager!")
if method == Y:
    final3 = int(wantmoney) - float(balance)
    ywait = input("Number of years you can wait: ")
    yconvert = int(ywait) * int(365)
    yconvert2 = int(final3) / int(yconvert)
    print("$Manager: You need to save up", final3, curr, " in", yconvert, "days")
    time.sleep(1)
    print("Which means,")
    time.sleep(1)
    final33 = float(final3) / float(yconvert)
    final333 = float(final33) * int(365)
    print("You need to save:", final333, curr, "in 1 year, for the whole of ", ywait, "year(s)!")
    final3333 = float(final333) / int(12)
    print(f"And {final3333} {curr} each month.")
    time.sleep(2)
    print("Please copy the information down.")
    time.sleep(10)
    print("Thank you for using $Manager!")



